### ISSUE TITLE
Setting button

### ISSUE THREAD

**Issue by andi216** [safi78/framb0ise#10]
Hi,
After updating "cams!" the setting button does not open. I have executed a clear cache.

**Comment by safi78** [comment]
Hi andi,

There was buggy version. Just reclone the latest, refresh cache, report back.

**Comment by jvanderzande** [comment]
I actually had the same issue and got it fixed in Chrome by doing:
F12/Application tab/Clear Storage 
Then reload and things worked again.
Jos

**Comment by andi216** [comment]
Yes ... it works now. Thank you very much.
