### ISSUE TITLE
Do not see any sensors on Android Full screen browser

### ISSUE THREAD

**Issue by boguslawb** [safi78/framb0ise#13]
Thanks for a nice domoticz board.! I tried it on old tablet but without success. I think this is where Domoticz has poor support and need better Android  dashboard. In framb0ise the same  sensors visible on ubuntu Chrome are not visible on old Android tablet with Full screen viewer installed. Domoticz alone works ok.

**Comment by safi78** [comment]
Hi bouslawb,

I'm not sure what browser you use on your Android dashboard. All functionality is tested with the latest Safari, Chrome and Firefox. If it doesn't work on 'older' browsers, that could be and probably will never be fixed.

**Comment by boguslawb** [comment]
It's a handy Android apk https://www.google.pl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi_wfaiouXTAhXld5oKHfikCpoQFggqMAA&url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dtk.klurige.fullscreenbrowser%26hl%3Dpl&usg=AFQjCNEriLTR4VUbzGYpZ_m7gIL_t3adWw&sig2=UqvZjrC_eWRkIlzRPeiaJA

It allows the full screen usage of tablet - ideal for dashboard.

**Comment by safi78** [comment]
Well, my Polish is pretty 'rusty' ;) 

I'm sorry, but I don't think this is 'supportable'. It either works on this, or it doesn't. Sorry!
