### ISSUE TITLE
Security panel code

### ISSUE THREAD

**Issue by andi216** [safi78/framb0ise#14]
In the security panel does not work the keys number from the window. It only works from the tablet keyboard or laptop keyboard. And when I open the security panel, the code stays typed.
![sec pannel](https://cloud.githubusercontent.com/assets/11821165/25971381/b447502c-36a4-11e7-802d-e6fdbdce2958.jpg)

**Comment by jvanderzande** [comment]
Not sure what your issue is, but currently the pin input field doesn't have the focus by default so you need to click the field first before typing the pin. I will create a pull request to set the focus for the pin field.

**Comment by jvanderzande** [comment]
Do you still have the issue with the latest version as things seems to be working properly for me?

Jos

**Comment by andi216** [comment]
Hi
I did not realize that there was a new update. Probably there were two updates at a short time. I apologise for my late answer. Everything works well now. Thank you very much.

**Comment by jvanderzande** [comment]
No problem and thanks for the feedback ;)
