### ISSUE TITLE
Temp hum is text only while temp is a bar with a level

### ISSUE THREAD

**Issue by tlpeter** [safi78/framb0ise#16]
Temp hum is text only while temp is a bar with a level.
Is it possible or desired to make the temp/hum also a bar for each value?

**Comment by jvanderzande** [comment]
How should this look like as the are 2 values to show... right?

Jos

**Comment by tlpeter** [comment]
Yes two values so i guess two bars.
It will look nicer i think.

**Comment by jvanderzande** [comment]
I have made a version that shows the 2 progressbars for Temp & Humidity. Not sure yet what the colors should be for the different levels of Humidity, but if you want you can have a play with it by getting it from my Fork before I make a Pull request. https://github.com/jvanderzande/framb0ise

**Comment by safi78** [comment]
Hi Guys,

@tlpeter any comments? I deliberately didn't put a bar for humidity because I didn't think it would look good. 

How do you like it?

**Comment by jvanderzande** [comment]
It actually doesn't look too bad, but am not particular about either way.   :)

**Comment by safi78** [comment]
Screenshot? :)

**Comment by jvanderzande** [comment]
As you wish :-) 
![knipsel](https://user-images.githubusercontent.com/13818504/29565829-da644d02-8747-11e7-93ed-be6d337ff3c9.PNG)

**Comment by tlpeter** [comment]
I am sorry, i totally forgot to take a look here.
I have copied the file in and yes it looks good.

Perhaps change the color for the hum is nice too but i do not know how this is now within Domoticz itself, does it change?

**Comment by jvanderzande** [comment]
There is logic in Framboise.js to set the appropriate color. 
Currently the colors will be:
- Green: between 50 -90 %
- Orange: Below 50%
- Red: Above 90%
Like I mentioned, this needs to be looked at what would be appropriate, but just wanted to share how it looks.

**Comment by safi78** [comment]
Jos, is this already in the master branch & can we close this?

**Comment by jvanderzande** [comment]
Nope...  So we want to make this a permanent change and if so, what should those thresholds for the colors be?
Jos

**Comment by safi78** [comment]
People like between 40-60%. So 0-39% = orange, 40-60%=green, 61-100% = orange?

**Comment by jvanderzande** [comment]
The changes are merged in. :)

**Comment by safi78** [comment]
Grazie mille! 👍
