### ISSUE TITLE
Dashboard keeps refreshing

### ISSUE THREAD

**Issue by maartenaalbers** [safi78/framb0ise#17]
Hi, 

After cloning the repo, I opened the dashboard and the page just kept refreshing. Like every second... And no devices are shown, even the settings button is not responding.

Maarten.

**Comment by jvanderzande** [comment]
Hi Maarten, do you have Rooms defined with devices in it in Domoticz under : "Setup/More Options/Plans/Roomplan?

Jos

**Comment by maartenaalbers** [comment]
Yes, a couple...

**Comment by jvanderzande** [comment]
What do you see in Chrome when doing F12 or Ctrl+Shift+I  - Developer mode)  and select the Console tab?
Does it show any errors?
Jos

**Comment by maartenaalbers** [comment]
I tried, but because of the refreshing, it disappears always. But there are red statements in the console.

**Comment by jvanderzande** [comment]
I will need information to understand what is happening.  Can you press the Stop button to make it stop looping?
You didn't put anything in the config yet? 
Maybe Clear the APP cache in DevMode by selecting Application/Clear Storage/press "Clear Site Data" button.

**Comment by safi78** [comment]
Is this 'fixed'?

**Comment by safi78** [comment]
No more info? Then I'll go ahead and close this, doesn't seem like a bug for the general public :)
