### ISSUE TITLE
Webcam unreachable

### ISSUE THREAD

**Issue by mjf2708** [safi78/framb0ise#24]
I have a webcam set up in Domoticz as follows:
Camera_2 address: 192.168.0.55 ImageURL: /html/cam_pic.php
It appears in the framb0ise Settings pane, and I have ticked it.
However, in framb0ise main screen shows 'Camera_2: unreachable!'
With debug switched on, I get the following messages in Firefox Web Console:
`Debug:init domoticzUrl:http://192.168.0.63:8080
framboise.js:1140:3
>Debug:End init:http://192.168.0.63:8080
framboise.js:1140:3
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
framb0ise
>Debug:Start UpdateCam timer`

**Comment by mjf2708** [comment]
Fixed this in framb0ise.js by removing camera username and password in function updateCams()
(but suggest there should be a test for no username / password)

**Comment by jvanderzande** [comment]
Not sure why you have issues. I have 2 camera's defined in domoticz without the userid/password filled in and both images are retrieved fine in framboise without any issue. 
what exactly did you change to make it work and how does the url to retrieve the image from the cam differ? (could you show the before and after urls?)

**Comment by mjf2708** [comment]
Hello Jos,

I’ve just checked this again.

Within Domoticz, the webcam is defined as:
Camera_2, address: 192.168.0.55, port: 80, ImageURL: /html/cam_pic.php

The following url in a browser updates the webcam images every second:
http://192.168.0 <http://192.168.0.0/>.55/html/

In framb0ise.js, with the following line (in function updateCams()) I get the error 'Camera_2: unreachable!':
var url = 'http://' + cam.Username + ':' + cam.Password + '@' + cam.Address + ':' + cam.Port + '/' + cam.ImageURL + '&' + new Date().getTime()

However, if I change this to:
var url = 'http://' + cam.Username + ':' + cam.Password + '@' + cam.Address + ':' + cam.Port + '/' + cam.ImageURL
then framb0ise shows webcam images OK (so it wasn’t the username & password).

Mike

**Comment by jvanderzande** [comment]
so the extra  '&' + new Date().getTime() is causing the issue? That is added to ensure that the image isn't coming from the browser cache  and always retrieved from the camera. It could be giving a problem because you don't have a "?" in your url yet. Could you try changing the line to the below to see whether that fixes it for you?:
var url = 'http://' + cam.Username + ':' + cam.Password + '@' + cam.Address + ':' + cam.Port + '/' + cam.ImageURL + '?' + new Date().getTime()
If that is the case we just need to add an check for '?' in the url.
Jos

**Comment by mjf2708** [comment]
Hi Jos,

Now working OK - thanks!

Mike

**Comment by jvanderzande** [comment]
Thanks for testing!
Could you try this latest version also on your system as that now tests for the presence of the "?" before adding the datetimevalue.
Jos

**Comment by mjf2708** [comment]
That version gives the error again.

This works OK:
var url = 'http://' + cam.Username + ':' + cam.Password + '@' + cam.Address + ':' + cam.Port + '/' + cam.ImageURL + "?" + new Date().getTime()

**Comment by jvanderzande** [comment]
Could you check what the exact URL was that it generated and retrieved so I can check whether it didn't use the  "?" in stead of the "&"? 
(use F12 - Network in chrome to check the url)

**Comment by jvanderzande** [comment]
I just setup some test cam to also be able to debug and think I git it nailed now with the latest change.
Could you give that a try too?

Thanks for testing,
Jos

**Comment by mjf2708** [comment]
Yes, OK now, thanks!

Mike
