### ISSUE TITLE
Devices shown twice

### ISSUE THREAD

**Issue by Tontze** [safi78/framb0ise#3]
In one room, all devices are shown twice, i presume this is because Door sensor and temperature sensor have same name ? 

![tekninen_tila](https://cloud.githubusercontent.com/assets/28216916/25562651/9ed6713c-2d94-11e7-909e-66fffc0ec06f.PNG)

`{
   "result" : [
      {
         "DevSceneRowID" : "98",
         "Name" : "Tekninen tila",
         "devidx" : "98",
         "idx" : "8",
         "order" : "8",
         "type" : 0
      },
      {
         "DevSceneRowID" : "105",
         "Name" : "Tekninen tila",
         "devidx" : "105",
         "idx" : "9",
         "order" : "9",
         "type" : 0
      }
   ],
   "status" : "OK",
   "title" : "GetPlanDevices"
}`

**Comment by jvanderzande** [comment]
So you have 2 devices with the exact same name doing different things? 
Will have a look but this is bound to give issues when you want to do any form of scripting logic as that works on device name, not idx.

**Comment by jvanderzande** [comment]
Closing this issue as solved.
