### ISSUE TITLE
Sorting of devices

### ISSUE THREAD

**Issue by safi78** [safi78/framb0ise#4]
Jos,

Could you take a look at the sometimes randomly sorting of devices on a refresh?

I THINK I followed the api's sorting method, but something goes wrong soenwhere, can't really find it.

**Comment by jvanderzande** [comment]
Will check to see what is happening and let you know.

**Comment by safi78** [comment]
Thanks for the fix!

**Comment by hvbommel** [comment]
It works great now, thanks !
