### ISSUE TITLE
Selector switches shows only state, cant change

### ISSUE THREAD

**Issue by Tontze** [safi78/framb0ise#4]
"MiLight test" in the picture

![milight_test](https://cloud.githubusercontent.com/assets/28216916/25562688/ae1a8e66-2d95-11e7-90d9-860deaf08e33.PNG)

**Comment by jvanderzande** [comment]
Selector switch isn't supported yet but will leave this open as a feature request to be implemented.

**Comment by jvanderzande** [comment]
Selector switch is available in the development branch and soon in the master when testing of the new functionality has been completed.
