### ISSUE TITLE
Jumping items

### ISSUE THREAD

**Issue by hvbommel** [safi78/framb0ise#5]
I have created a roomplan called "Inputs" and it contains Input1..Input8. Each time I refresh the framb0ise screen the inputs are displayed in a different order, they jump around. It would be nice if they where always displayed in a same and sorted order. Another plan called "Relays" containing 8 relays has the same behavior.

**Comment by safi78** [comment]
fixed by jvanderzande

**Comment by hvbommel** [comment]
It works great now ! thanks
